// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDFW5PQmPj6F5jlGAz7-EwWoJHcbIRM38',
    appId: '1:682836469520:web:1c7a5d931c1612da736795',
    messagingSenderId: '682836469520',
    projectId: 'neew-d0bdd',
    authDomain: 'neew-d0bdd.firebaseapp.com',
    databaseURL: 'https://neew-d0bdd.firebaseio.com',
    storageBucket: 'neew-d0bdd.firebasestorage.app',
    measurementId: 'G-8ND6TNE895',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc7j67M9dTjK7wFTlVNSIdeTmAib_Mjj4',
    appId: '1:682836469520:android:a8d28c80554a785d736795',
    messagingSenderId: '682836469520',
    projectId: 'neew-d0bdd',
    databaseURL: 'https://neew-d0bdd.firebaseio.com',
    storageBucket: 'neew-d0bdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBljn87MV6Ebc0_zQv1YSzjl6ByhnkPCL0',
    appId: '1:682836469520:ios:11f33e09ec0e555a736795',
    messagingSenderId: '682836469520',
    projectId: 'neew-d0bdd',
    databaseURL: 'https://neew-d0bdd.firebaseio.com',
    storageBucket: 'neew-d0bdd.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );
}
